services:
  create:
    image: ms_create
    container_name: ms_create
    build:
      context: .
      dockerfile: Dockerfile-cs
      args:
        MYSQL_PASSWORD: abc
    depends_on:
      - mysql
    environment:
      RMI_REMOTE_HOST: ms_create
      RMI_REMOTE_PORT: 1099
      MYSQL_REMOTE_HOST: ms_mysql
      MYSQL_REMOTE_PORT: 3306
    networks:
      - ms

  retrieve:
    image: ms_retrieve
    container_name: ms_retrieve
    build:
      context: .
      dockerfile: Dockerfile-rs
      args:
        MYSQL_PASSWORD: abc
    depends_on:
      - mysql
    environment:
      RMI_REMOTE_HOST: ms_retrieve
      RMI_REMOTE_PORT: 1098
      MYSQL_REMOTE_HOST: ms_mysql
      MYSQL_REMOTE_PORT: 3306
    networks:
      - ms

  delete:
    image: ms_delete
    container_name: ms_delete
    build:
      context: .
      dockerfile: Dockerfile-ds
      args:
        MYSQL_PASSWORD: abc
    depends_on:
      - mysql
    environment:
      RMI_REMOTE_HOST: ms_delete
      RMI_REMOTE_PORT: 1097
      MYSQL_REMOTE_HOST: ms_mysql
      MYSQL_REMOTE_PORT: 3306
    networks:
      - ms

  client:
    image: ms_client
    container_name: ms_client
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile-msc
    command: java OrdersUI
    environment:
      RMI_REMOTE_HOST: ms_server
      RMI_REMOTE_PORT: 1099
    networks:
      - ms

  auth:
      image: ms_auth
      container_name: ms_auths
      build:
        context: .
        dockerfile: Dockerfile-auth
        args:
          MYSQL_PASSWORD: foo
      depends_on:
        - mysql
      environment:
        RMI_REMOTE_HOST: ms_auth
        RMI_REMOTE_PORT: 1096
        MYSQL_REMOTE_HOST: ms_mysql
        MYSQL_REMOTE_PORT: 3306
      networks:
        - ms

  mysql:
    image: mysql:5
    platform: linux/amd64
    container_name: ms_mysql
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ms_db:/var/lib/mysql
    environment:
      "MYSQL_ROOT_PASSWORD": abc
      "MYSQL_DATABASE": ms_orderinfo
      "MYSQL_HOST": ms_mysql
    expose:
      - 3306
    networks:
      - ms

networks:
  ms:
volumes:
  ms_db:
    external: true

